package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approver implements Serializable {

    static final long serialVersionUID = 1L;

    private int id;
    private String firstName;
    private String lastName;
    private String userName;
    private String emailAddress;
    private String randomAccessKey;

    public Approver() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    
    public String getRandomAccessKey() {
        return this.randomAccessKey;
    }
    
    public void setRandomAccessKey(String randomAccessKey) {
        this.randomAccessKey = randomAccessKey;
    }

    public Approver(String userName, String emailAddress, String firstName, String lastName, String randomAccessKey) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.emailAddress = emailAddress;
        this.randomAccessKey = randomAccessKey;
    }
    
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Approver: ");
        sb.append("\n firstName: ");
        sb.append(this.firstName);
        sb.append("\n lastName: ");
        sb.append(this.lastName);
        sb.append("\n userName: ");
        sb.append( this.userName);
        sb.append("\n emailAddress: ");
        sb.append( this.emailAddress);
        sb.append("\n randomAccessKey: ");
        sb.append(this.randomAccessKey);

        return sb.toString();
    }

}
