package com.redhat.management.approval;

import java.util.ArrayList;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApproveEmailList implements Serializable {

    static final long serialVersionUID = 1L;

    private ArrayList<ApproveEmail> emails;

    public ApproveEmailList() {
    }

    public ArrayList<ApproveEmail> getEmails() {
        return this.emails;
    }

    public void setEmails(
            ArrayList<ApproveEmail> emails) {
        this.emails = emails;
    }

    public ApproveEmailList(ArrayList<ApproveEmail> emails) {
        this.emails = emails;
    }

}
