package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Approver implements Serializable {

    static final long serialVersionUID = 1L;

    private int id;
    private String firstName;
    private String lastName;
    private String userName;
    private String emailAddress;

    public Approver() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public Approver(String userName, String emailAddress, String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.emailAddress = emailAddress;
    }
    
    public String toString() {
        return "Approver: " +
        "\n firstName: " + this.firstName +
        "\n lastName: " + this.lastName +
        "\n userName: " + this.userName +
        "\n emailAddress: " + this.emailAddress;
    }

}
