package com.redhat.management.approval;
import java.util.ArrayList;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApproveEmail implements Serializable {

    static final long serialVersionUID = 1L;

    private String subject;
    private String bodyType;
    private String body;
    private ArrayList<String> recipients;

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getBodyType() {
        return this.bodyType;
    }

    public void setBodyType(String bodyType) {
        this.bodyType = bodyType;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }
    
    public void setBody(Request request,
                        Approver approver,
                        Group group,
                        ArrayList<Stage> stages) {
        ApproveEmailBody body = new ApproveEmailBody(request, approver, group, stages);
        this.body = body.getEmailBody();
    }


    public ArrayList<String> getRecipients() {
        return this.recipients;
    }

    public void setRecipents(ArrayList<String> recipients) {
        this.recipients = recipients;
    }

    public ApproveEmail(ArrayList<String> recipients) {
        this.subject = "Catalog : Approval Order ";
        this.bodyType = "html";
        this.body = "";
        this.recipients = recipients;
    }

}
