package com.redhat.management.approval;

import java.util.ArrayList;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Group implements Serializable {

    static final long serialVersionUID = 1L;

    private String name;
    private ArrayList<Approver> approvers;
    private String description;
    private String uuid;

    public Group() {
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArrayList<Approver> getApprovers() {
        return this.approvers;
    }

    public void setApprovers(
        ArrayList<Approver> approvers) {
        this.approvers = approvers;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String toString() {
        String groupStr = "\nGroup: " + "\n name: " + this.name
                + "\n description: " + this.description + "\n ref: " + this.uuid;

        for (Approver approver : approvers) {
            groupStr = groupStr + approver;
        }
        return groupStr;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Group(String name,
            ArrayList<Approver> approvers,
            String description, String uuid) {
        this.name = name;
        this.approvers = approvers;
        this.description = description;
        this.uuid = uuid;
    }

}
