package com.redhat.management.approval;

import java.util.List;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Group implements Serializable {

    static final long serialVersionUID = 1L;

    private String name;
    private List<Approver> approvers;
    private String uuid;

    public Group() {
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Approver> getApprovers() {
        return this.approvers;
    }

    public void setApprovers(List<Approver> approvers) {
        this.approvers = approvers;
    }

    public String toString() {
        String groupStr = "Group: " + "\n name: " + this.name
                + "\n ref: " + this.uuid;

        for (Approver approver : approvers) {
            groupStr = groupStr + approver;
        }
        return groupStr;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Group(String name, List<Approver> approvers, String uuid) {
        this.name = name;
        this.approvers = approvers;
        this.uuid = uuid;
    }

}
