package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Identity implements Serializable {

    static final long serialVersionUID = 1L;

    private String account_number;
    private String type;
    private User user;
    private Internal internal;

    public Identity() {
    }

    public String getAccount_number() {
        return this.account_number;
    }

    public void setAccount_number(String account_number) {
        this.account_number = account_number;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Internal getInternal() {
        return this.internal;
    }

    public void setInternal(Internal internal) {
        this.internal = internal;
    }

    public Identity(String account_number, String type,
            User user,
            Internal internal) {
        this.account_number = account_number;
        this.type = type;
        this.user = user;
        this.internal = internal;
    }
    
    public String toString() {
    return "Identity: " +
      "\n   account_number: " + account_number +
      "\n   type: " + type +
      "\n   : " + user +
      "\n   internal: " + internal;
    }

}
