package com.redhat.management.approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Identity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String account_number;
    private java.lang.String type;
    private com.redhat.management.approval.User user;
    private com.redhat.management.approval.Internal internal;

    public Identity() {
    }

    public java.lang.String getAccount_number() {
        return this.account_number;
    }

    public void setAccount_number(java.lang.String account_number) {
        this.account_number = account_number;
    }

    public java.lang.String getType() {
        return this.type;
    }

    public void setType(java.lang.String type) {
        this.type = type;
    }

    public com.redhat.management.approval.User getUser() {
        return this.user;
    }

    public void setUser(com.redhat.management.approval.User user) {
        this.user = user;
    }

    public com.redhat.management.approval.Internal getInternal() {
        return this.internal;
    }

    public void setInternal(com.redhat.management.approval.Internal internal) {
        this.internal = internal;
    }

    public Identity(java.lang.String account_number, java.lang.String type,
            com.redhat.management.approval.User user,
            com.redhat.management.approval.Internal internal) {
        this.account_number = account_number;
        this.type = type;
        this.user = user;
        this.internal = internal;
    }
    
    public String toString() {
    return "Identity: " +
      "\n   account_number: " + account_number +
      "\n   type: " + type +
      "\n   : " + user +
      "\n   internal: " + internal;
    }

}
