package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Internal implements Serializable {

    static final long serialVersionUID = 1L;

    // This class models an internal object passed in as a map.
    // The attribute names must exactly match the keys in the map for object mapping.
    private String org_id;
    private String auth_type;
    private int auth_time;

    public Internal() {
    }

    public String getOrg_id() {
        return this.org_id;
    }

    public void setOrg_id(String org_id) {
        this.org_id = org_id;
    }

    public String getAuth_type() {
        return this.auth_type;
    }

    public void setAuth_type(String auth_type) {
        this.auth_type = auth_type;
    }

    public int getAuth_time() {
        return this.auth_time;
    }

    public void setAuth_time(int auth_time) {
        this.auth_time = auth_time;
    }

    public Internal(String org_id, String auth_type,
            int auth_time) {
        this.org_id = org_id;
        this.auth_type = auth_type;
        this.auth_time = auth_time;
    }

}
