package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recipient implements Serializable {

    static final long serialVersionUID = 1L;

    private String name;
    private String email;

    public Recipient() {
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String toString() {
        return email;
    }

    public Recipient(String name, String email) {
        this.name = name;
        this.email = email;
    }

}
