package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RHIdentity implements Serializable {

    static final long serialVersionUID = 1L;

    private Identity identity;

    public RHIdentity() {
    }

    public Identity getIdentity() {
        return this.identity;
    }

    public void setIdentity(Identity identity) {
        this.identity = identity;
    }

    public RHIdentity(Identity identity) {
        this.identity = identity;
    }
    
    public User getUser() {
        return getIdentity().getUser();
    }
    
    public String toString() {
        return "RHIdentity: " + identity;
    }

}
