package com.redhat.management.approval;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Stage implements Serializable {

    static final long serialVersionUID = 1L;

    private String id;
    private String randomAccessKey;
    private String createdTime;
    private String groupRef;

    public Stage() {
    }

    public String getRandomAccessKey() {
        return this.randomAccessKey;
    }

    public void setRandomAccessKey(String randomAccessKey) {
        this.randomAccessKey = randomAccessKey;
    }

    public String getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGroupRef() {
        return this.groupRef;
    }

    public void setGroupRef(String groupRef) {
        this.groupRef = groupRef;
    }

    public Stage(String id, String randomAccessKey,
            String createdTime, String groupRef) {
        this.id = id;
        this.randomAccessKey = randomAccessKey;
        this.createdTime = createdTime;
        this.groupRef = groupRef;
    }
    
    public String toString() {
        return "\nStage:" +
          "\n   id: " + id +
          "\n   random access key: " + randomAccessKey +
          "\n   group ref: " + groupRef +
          "\n   createdTime: " + createdTime;
    }
}
